# Generated by Django 4.2.3 on 2025-01-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_color_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('White', 'White'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Vilolet', 'Violet'), ('Navy blue', 'Navy blue'), ('Light Pink', 'Light Pink'), ('Gray', 'Gray'), ('Maroon', 'Maroon'), ('Orange', 'Orange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4(38)', '4(38)'), ('5(39)', '5(39)'), ('6(40)', '6(40)'), ('7(41)', '7(41)'), ('8(42)', '8(42)')], max_length=5),
        ),
    ]
